import React, {useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,useLocation,useNavigate} from 'react-router-dom';
import {signInAnonymously,signInWithEmailAndPassword,signOut,onAuthStateChanged} from 'firebase/auth';
import {collection,deleteDoc,doc,getDoc,getDocs,onSnapshot,orderBy,query,serverTimestamp,setDoc,updateDoc,writeBatch} from 'firebase/firestore';
import QRCode from 'qrcode';
import {auth,db} from './firebase';
import {questions} from './questions';
import './styles.css';

const pointsPerCorrect=100;
const getSession=()=>new URLSearchParams(location.search).get('session')||localStorage.getItem('kelly_session')||'';
const initials=n=>n.trim().split(/\s+/).map((x,i,a)=>i===0||i===a.length-1?x[0].toUpperCase()+'.':'').filter(Boolean).join(' ');
const fmt=ms=>`${String(Math.floor(ms/60000)).padStart(2,'0')}:${String(Math.floor(ms%60000/1000)).padStart(2,'0')}`;
async function emailKey(email){const data=new TextEncoder().encode(email.trim().toLowerCase());const hash=await crypto.subtle.digest('SHA-256',data);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function Shell({children,wide=false}){return <main className={wide?'shell wide':'shell'}><div className="brand"><span>KELLY EDUCATION</span><strong>SUBSTITUTE TEACHER CHALLENGE</strong></div>{children}</main>}
function Loading(){return <Shell><section className="card center"><div className="spinner"/><p>Getting the challenge ready…</p></section></Shell>}

function Play(){const nav=useNavigate();const [name,setName]=useState('');const [email,setEmail]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const sid=getSession();
 async function start(e){e.preventDefault();setBusy(true);setError('');try{let activeSid=sid;if(!activeSid){const openSessions=(await getDocs(collection(db,'sessions'))).docs.filter(x=>x.data().status==='open');if(openSessions.length===1)activeSid=openSessions[0].id;else if(openSessions.length>1)throw Error('More than one session is open. Please scan the QR code for your orientation.');else throw Error('There is no open session yet. Please ask the administrator to open one.')}const s=await getDoc(doc(db,'sessions',activeSid));if(!s.exists()||s.data().status!=='open')throw Error('This session is not open yet.');const id=await emailKey(email);const ref=doc(db,'sessions',activeSid,'participants',id);const existing=await getDoc(ref);localStorage.setItem('kelly_session',activeSid);localStorage.setItem('kelly_player',id);if(existing.exists()){if(existing.data().ownerUid!==auth.currentUser.uid)throw Error('This email has already joined this session.');if(existing.data().completed){nav(`/results?session=${activeSid}`);return}if(!localStorage.getItem('kelly_start'))localStorage.setItem('kelly_start',String(Date.now()));nav(`/quiz?session=${activeSid}`);return}await setDoc(ref,{ownerUid:auth.currentUser.uid,displayName:initials(name),score:0,correct:0,elapsedMs:0,completed:false,joinedAt:serverTimestamp()});localStorage.setItem('kelly_start',String(Date.now()));nav(`/quiz?session=${activeSid}`)}catch(x){setError(x.message)}finally{setBusy(false)}}
 return <Shell><section className="hero"><p className="eyebrow">LIVE ORIENTATION GAME</p><h1>Think you know the classroom rules?</h1><p>15 questions. A or B. Choose wisely.</p></section><form className="card form" onSubmit={start}><label>FULL NAME<input required minLength="2" autoComplete="name" value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/></label><label>EMAIL ADDRESS<input required type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label>{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?'JOINING…':'START CHALLENGE'}</button></form></Shell>}

function Quiz(){const nav=useNavigate();const sid=getSession(),pid=localStorage.getItem('kelly_player');const [i,setI]=useState(0),[score,setScore]=useState(0),[choice,setChoice]=useState(null);const start=Number(localStorage.getItem('kelly_start'))||Date.now();if(!pid){nav(`/play?session=${sid}`);return null}const item=questions[i];
 function answer(value){if(choice!==null)return;setChoice(value);const right=value===item.a;const next=score+(right?pointsPerCorrect:0);setTimeout(async()=>{if(i===questions.length-1){const elapsed=Date.now()-start;await updateDoc(doc(db,'sessions',sid,'participants',pid),{score:next,correct:next/pointsPerCorrect,elapsedMs:elapsed,completed:true,completedAt:serverTimestamp()});nav(`/results?session=${sid}`)}else{setScore(next);setI(i+1);setChoice(null)}},1450)}
 return <Shell><section className="quizHead"><span>QUESTION {i+1} OF {questions.length}</span><b>{score} PTS</b></section><div className="progress"><i style={{width:`${(i+1)/questions.length*100}%`}}/></div><section className="card question"><h2>{item.q}</h2><div className="answers"><button className={choice===true?(item.a?'correct':'wrong'):''} onClick={()=>answer(true)} disabled={choice!==null}><b>A</b> YES</button><button className={choice===false?(!item.a?'correct':'wrong'):''} onClick={()=>answer(false)} disabled={choice!==null}><b>B</b> NO</button></div>{choice!==null&&<div className={choice===item.a?'feedback good':'feedback'}><strong>{choice===item.a?'CORRECT!':'NOT QUITE'}</strong><span>{item.e}</span></div>}</section></Shell>}

function Results(){const [p,setP]=useState(null),[rank,setRank]=useState(null);const sid=getSession(),pid=localStorage.getItem('kelly_player');useEffect(()=>onSnapshot(collection(db,'sessions',sid,'participants'),snap=>{const all=snap.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.completed).sort((a,b)=>b.score-a.score||a.elapsedMs-b.elapsedMs);setP(all.find(x=>x.id===pid));setRank(all.findIndex(x=>x.id===pid)+1)}),[]);if(!p)return <Loading/>;return <Shell><section className="card result center"><div className="check">✓</div><p className="eyebrow">CHALLENGE COMPLETE</p><h1>{p.correct} / 15 <small>CORRECT</small></h1><div className="stats"><div><b>{p.score}</b><span>POINTS</span></div><div><b>{fmt(p.elapsedMs)}</b><span>TIME</span></div><div><b>#{rank}</b><span>RANK</span></div></div><p>Great job! Check the live leaderboard.</p><a className="primary link" href={`/leaderboard?session=${sid}`}>VIEW LEADERBOARD</a></section></Shell>}

function Leaderboard(){const sid=getSession();const [session,setSession]=useState(null),[players,setPlayers]=useState([]);useEffect(()=>{if(!sid)return;const a=onSnapshot(doc(db,'sessions',sid),s=>setSession(s.data()));const b=onSnapshot(collection(db,'sessions',sid,'participants'),snap=>setPlayers(snap.docs.map(d=>({id:d.id,...d.data()}))));return()=>{a();b()}},[sid]);const done=players.filter(x=>x.completed).sort((a,b)=>b.score-a.score||a.elapsedMs-b.elapsedMs).slice(0,10);return <Shell wide><section className="boardTitle"><p>{session?.name||'LIVE SESSION'}</p><h1>LIVE LEADERBOARD</h1><div><b>PLAYERS: {players.length}</b><b>COMPLETED: {players.filter(x=>x.completed).length}</b></div></section><section className="leaderboard">{done.length?done.map((p,i)=><div className={`row place${i+1}`} key={p.id}><span className="place">{i===0?'🏆':i===1?'🥈':i===2?'🥉':i+1}</span><strong>{p.displayName}</strong><span>{p.score}</span><small>{fmt(p.elapsedMs)}</small></div>):<div className="waiting">Waiting for the first finisher…</div>}</section></Shell>}

function Admin(){const [user,setUser]=useState(auth.currentUser?.isAnonymous?null:auth.currentUser);const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[err,setErr]=useState(''),[sessions,setSessions]=useState([]),[selected,setSelected]=useState(''),[name,setName]=useState(''),[qr,setQr]=useState(''),[participants,setParticipants]=useState([]);useEffect(()=>onAuthStateChanged(auth,u=>setUser(u&&!u.isAnonymous?u:null)),[]);useEffect(()=>{if(!user)return;return onSnapshot(collection(db,'sessions'),s=>setSessions(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0))))},[user]);useEffect(()=>{if(!selected)return;return onSnapshot(collection(db,'sessions',selected,'participants'),s=>setParticipants(s.docs.map(d=>d.data())))},[selected]);useEffect(()=>{if(selected)QRCode.toDataURL(`${location.origin}/play?session=${selected}`,{width:420,margin:1,color:{dark:'#172b3a',light:'#ffffff'}}).then(setQr)},[selected]);
 async function login(e){e.preventDefault();try{if(auth.currentUser?.isAnonymous)await signOut(auth);await signInWithEmailAndPassword(auth,email,password)}catch(x){setErr('Unable to sign in. Check the administrator credentials.')}}async function create(){const id=(name||`orientation-${Date.now()}`).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');await setDoc(doc(db,'sessions',id),{name:name||id,status:'closed',createdAt:serverTimestamp()});setSelected(id);setName('')}async function status(v){await updateDoc(doc(db,'sessions',selected),{status:v})}async function reset(){if(!confirm('Delete every participant and result in this session?'))return;const snap=await getDocs(collection(db,'sessions',selected,'participants'));for(let i=0;i<snap.docs.length;i+=400){const batch=writeBatch(db);snap.docs.slice(i,i+400).forEach(x=>batch.delete(x.ref));await batch.commit()}}if(!user)return <Shell><form className="card form adminLogin" onSubmit={login}><h1>Administrator</h1><label>EMAIL<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>PASSWORD<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{err&&<p className="error">{err}</p>}<button className="primary">SIGN IN</button></form></Shell>;
 const current=sessions.find(x=>x.id===selected);return <Shell wide><section className="adminTop"><div><p className="eyebrow">CONTROL ROOM</p><h1>Administrator Dashboard</h1></div><button className="ghost" onClick={()=>signOut(auth)}>SIGN OUT</button></section><section className="adminGrid"><div className="card"><h2>Create new session</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="Miami Orientation — August 14, 2026"/><button className="primary" onClick={create}>CREATE SESSION</button><h3>Sessions</h3><div className="sessionList">{sessions.map(s=><button className={selected===s.id?'active':''} onClick={()=>setSelected(s.id)} key={s.id}><span>{s.name}</span><b>{s.status}</b></button>)}</div></div><div className="card controls">{current?<><div className="status"><span className={current.status}/>{current.status.toUpperCase()}</div><h2>{current.name}</h2><code>{current.id}</code><div className="buttonRow"><button onClick={()=>status('open')}>OPEN SESSION</button><button onClick={()=>status('closed')}>CLOSE SESSION</button><button className="danger" onClick={reset}>RESET SESSION</button></div><div className="adminStats"><b>{participants.length}<small> PLAYERS</small></b><b>{participants.filter(p=>p.completed).length}<small> COMPLETED</small></b></div><div className="qrArea">{qr&&<img src={qr}/>}<div><p>Participant link</p><a href={`/play?session=${selected}`}>{location.origin}/play?session={selected}</a><a className="primary link" target="_blank" href={`/leaderboard?session=${selected}`}>SHOW LEADERBOARD / WINNER</a></div></div><div className="resultsTable">{participants.sort((a,b)=>b.score-a.score||a.elapsedMs-b.elapsedMs).map((p,i)=><div key={`${p.displayName}-${i}`}><b>{i+1}. {p.displayName}</b><span>{p.completed?`${p.score} pts · ${fmt(p.elapsedMs)}`:'Playing'}</span></div>)}</div></>:<div className="empty">Create or select a session to begin.</div>}</div></section></Shell>}

function App(){const [ready,setReady]=useState(false);useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u&&location.pathname!=='/admin')await signInAnonymously(auth);setReady(true)}),[]);if(!ready)return <Loading/>;const p=location.pathname;if(p==='/quiz')return <Quiz/>;if(p==='/results')return <Results/>;if(p==='/leaderboard')return <Leaderboard/>;if(p==='/admin')return <Admin/>;return <Play/>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
