export const questions = [
  {q:'Your assignment begins at 8:00 a.m. You arrive at 7:45 to check in, locate the classroom, and review the day’s plans. Is this the recommended approach?',a:true,e:'Excellent preparation starts with arriving at least 15 minutes early.'},
  {q:'The lesson plan looks straightforward, but it includes links and attachments. Should you review all materials before students arrive?',a:true,e:'Reviewing every resource in advance helps instruction begin smoothly and confidently.'},
  {q:'Students are following a casual spirit-day dress code. May you also wear jeans or Crocs when substitute guidelines do not permit them?',a:false,e:'Substitutes should follow Kelly Education’s business-professional dress expectations.'},
  {q:'Students begin independent work and the room is quiet. Is this an appropriate time to check personal messages?',a:false,e:'Your full attention and active supervision are needed throughout the class period.'},
  {q:'A student proudly shows you a creative classroom display. May you photograph it if no students are visible?',a:false,e:'Protect school privacy by never photographing classrooms, materials, or displays.'},
  {q:'After a successful activity, students ask you to join a group selfie. Should you politely decline?',a:true,e:'Yes. Never photograph students or appear in student photos while on assignment.'},
  {q:'A student says your lesson was helpful and asks to follow your public social-media account. Is it appropriate to share your username?',a:false,e:'Keep all relationships professional and do not connect with students on social media.'},
  {q:'A student asks for your personal number so they can contact you about an assignment later. Should you direct them to their teacher or school instead?',a:true,e:'Use approved school communication channels and never share personal contact information.'},
  {q:'You need to step out briefly, and the class appears settled. May you leave students unattended while you are gone?',a:false,e:'Contact the office for assistance or coverage; students must never be left unattended.'},
  {q:'During lunch, you would like to pick up food nearby. May you leave campus when the school requires substitutes to remain onsite?',a:false,e:'Follow the school’s onsite policy and confirm expectations with the front office.'},
  {q:'The teacher has snacks stored in the classroom. May you offer them as prizes without written permission?',a:false,e:'Do not consume or distribute a teacher’s food, candy, or personal supplies without approval.'},
  {q:'The teacher’s notes differ slightly from what students say they usually do. Should you follow the written plan and contact the office if clarification is needed?',a:true,e:'The teacher’s instructions are your guide; seek support instead of improvising major changes.'},
  {q:'A challenging classroom moment would make an interesting anonymous social-media post. Is sharing it acceptable if you omit names?',a:false,e:'Classroom experiences and student information must remain private, even without names.'},
  {q:'Your smartwatch and phone are silenced and stored away before instruction begins. Is this a professional classroom practice?',a:true,e:'Keeping personal devices out of use supports focus, safety, and professional presence.'},
  {q:'A student refuses to follow a direction. Should you respond calmly, follow the classroom management plan, and request school support when needed?',a:true,e:'Stay calm, use the established procedures, document concerns, and ask for support.'}
];
